package com.tbe.beans;

public class Local {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local.L_N
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String lN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column local.color
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String color;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local.ID
     *
     * @return the value of local.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local.ID
     *
     * @param id the value for local.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local.L_N
     *
     * @return the value of local.L_N
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getlN() {
        return lN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local.L_N
     *
     * @param lN the value for local.L_N
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setlN(String lN) {
        this.lN = lN == null ? null : lN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column local.color
     *
     * @return the value of local.color
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column local.color
     *
     * @param color the value for local.color
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }
}