package com.tbe.beans;

public class Machine {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_tb.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column machine_tb.Ma_Name
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String maName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_tb.ID
     *
     * @return the value of machine_tb.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_tb.ID
     *
     * @param id the value for machine_tb.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column machine_tb.Ma_Name
     *
     * @return the value of machine_tb.Ma_Name
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getMaName() {
        return maName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column machine_tb.Ma_Name
     *
     * @param maName the value for machine_tb.Ma_Name
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setMaName(String maName) {
        this.maName = maName == null ? null : maName.trim();
    }
}