package com.tbe.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PUIDExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public PUIDExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPuidIsNull() {
            addCriterion("PUID is null");
            return (Criteria) this;
        }

        public Criteria andPuidIsNotNull() {
            addCriterion("PUID is not null");
            return (Criteria) this;
        }

        public Criteria andPuidEqualTo(String value) {
            addCriterion("PUID =", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidNotEqualTo(String value) {
            addCriterion("PUID <>", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidGreaterThan(String value) {
            addCriterion("PUID >", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidGreaterThanOrEqualTo(String value) {
            addCriterion("PUID >=", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidLessThan(String value) {
            addCriterion("PUID <", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidLessThanOrEqualTo(String value) {
            addCriterion("PUID <=", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidLike(String value) {
            addCriterion("PUID like", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidNotLike(String value) {
            addCriterion("PUID not like", value, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidIn(List<String> values) {
            addCriterion("PUID in", values, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidNotIn(List<String> values) {
            addCriterion("PUID not in", values, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidBetween(String value1, String value2) {
            addCriterion("PUID between", value1, value2, "puid");
            return (Criteria) this;
        }

        public Criteria andPuidNotBetween(String value1, String value2) {
            addCriterion("PUID not between", value1, value2, "puid");
            return (Criteria) this;
        }

        public Criteria andZdCodeIsNull() {
            addCriterion("ZD_Code is null");
            return (Criteria) this;
        }

        public Criteria andZdCodeIsNotNull() {
            addCriterion("ZD_Code is not null");
            return (Criteria) this;
        }

        public Criteria andZdCodeEqualTo(String value) {
            addCriterion("ZD_Code =", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeNotEqualTo(String value) {
            addCriterion("ZD_Code <>", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeGreaterThan(String value) {
            addCriterion("ZD_Code >", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ZD_Code >=", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeLessThan(String value) {
            addCriterion("ZD_Code <", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeLessThanOrEqualTo(String value) {
            addCriterion("ZD_Code <=", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeLike(String value) {
            addCriterion("ZD_Code like", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeNotLike(String value) {
            addCriterion("ZD_Code not like", value, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeIn(List<String> values) {
            addCriterion("ZD_Code in", values, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeNotIn(List<String> values) {
            addCriterion("ZD_Code not in", values, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeBetween(String value1, String value2) {
            addCriterion("ZD_Code between", value1, value2, "zdCode");
            return (Criteria) this;
        }

        public Criteria andZdCodeNotBetween(String value1, String value2) {
            addCriterion("ZD_Code not between", value1, value2, "zdCode");
            return (Criteria) this;
        }

        public Criteria andMachineIdIsNull() {
            addCriterion("Machine_ID is null");
            return (Criteria) this;
        }

        public Criteria andMachineIdIsNotNull() {
            addCriterion("Machine_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMachineIdEqualTo(String value) {
            addCriterion("Machine_ID =", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdNotEqualTo(String value) {
            addCriterion("Machine_ID <>", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdGreaterThan(String value) {
            addCriterion("Machine_ID >", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdGreaterThanOrEqualTo(String value) {
            addCriterion("Machine_ID >=", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdLessThan(String value) {
            addCriterion("Machine_ID <", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdLessThanOrEqualTo(String value) {
            addCriterion("Machine_ID <=", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdLike(String value) {
            addCriterion("Machine_ID like", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdNotLike(String value) {
            addCriterion("Machine_ID not like", value, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdIn(List<String> values) {
            addCriterion("Machine_ID in", values, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdNotIn(List<String> values) {
            addCriterion("Machine_ID not in", values, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdBetween(String value1, String value2) {
            addCriterion("Machine_ID between", value1, value2, "machineId");
            return (Criteria) this;
        }

        public Criteria andMachineIdNotBetween(String value1, String value2) {
            addCriterion("Machine_ID not between", value1, value2, "machineId");
            return (Criteria) this;
        }

        public Criteria andODtIsNull() {
            addCriterion("O_DT is null");
            return (Criteria) this;
        }

        public Criteria andODtIsNotNull() {
            addCriterion("O_DT is not null");
            return (Criteria) this;
        }

        public Criteria andODtEqualTo(Date value) {
            addCriterion("O_DT =", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotEqualTo(Date value) {
            addCriterion("O_DT <>", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtGreaterThan(Date value) {
            addCriterion("O_DT >", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtGreaterThanOrEqualTo(Date value) {
            addCriterion("O_DT >=", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtLessThan(Date value) {
            addCriterion("O_DT <", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtLessThanOrEqualTo(Date value) {
            addCriterion("O_DT <=", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtIn(List<Date> values) {
            addCriterion("O_DT in", values, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotIn(List<Date> values) {
            addCriterion("O_DT not in", values, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtBetween(Date value1, Date value2) {
            addCriterion("O_DT between", value1, value2, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotBetween(Date value1, Date value2) {
            addCriterion("O_DT not between", value1, value2, "oDt");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("Operator_ID is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("Operator_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(String value) {
            addCriterion("Operator_ID =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(String value) {
            addCriterion("Operator_ID <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(String value) {
            addCriterion("Operator_ID >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("Operator_ID >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(String value) {
            addCriterion("Operator_ID <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("Operator_ID <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLike(String value) {
            addCriterion("Operator_ID like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotLike(String value) {
            addCriterion("Operator_ID not like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<String> values) {
            addCriterion("Operator_ID in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<String> values) {
            addCriterion("Operator_ID not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(String value1, String value2) {
            addCriterion("Operator_ID between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(String value1, String value2) {
            addCriterion("Operator_ID not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andPassDtIsNull() {
            addCriterion("Pass_DT is null");
            return (Criteria) this;
        }

        public Criteria andPassDtIsNotNull() {
            addCriterion("Pass_DT is not null");
            return (Criteria) this;
        }

        public Criteria andPassDtEqualTo(Date value) {
            addCriterion("Pass_DT =", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtNotEqualTo(Date value) {
            addCriterion("Pass_DT <>", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtGreaterThan(Date value) {
            addCriterion("Pass_DT >", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtGreaterThanOrEqualTo(Date value) {
            addCriterion("Pass_DT >=", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtLessThan(Date value) {
            addCriterion("Pass_DT <", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtLessThanOrEqualTo(Date value) {
            addCriterion("Pass_DT <=", value, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtIn(List<Date> values) {
            addCriterion("Pass_DT in", values, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtNotIn(List<Date> values) {
            addCriterion("Pass_DT not in", values, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtBetween(Date value1, Date value2) {
            addCriterion("Pass_DT between", value1, value2, "passDt");
            return (Criteria) this;
        }

        public Criteria andPassDtNotBetween(Date value1, Date value2) {
            addCriterion("Pass_DT not between", value1, value2, "passDt");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("Check_ID is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("Check_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("Check_ID =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("Check_ID <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("Check_ID >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("Check_ID >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("Check_ID <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("Check_ID <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("Check_ID like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("Check_ID not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("Check_ID in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("Check_ID not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("Check_ID between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("Check_ID not between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andRDtIsNull() {
            addCriterion("R_DT is null");
            return (Criteria) this;
        }

        public Criteria andRDtIsNotNull() {
            addCriterion("R_DT is not null");
            return (Criteria) this;
        }

        public Criteria andRDtEqualTo(Date value) {
            addCriterion("R_DT =", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtNotEqualTo(Date value) {
            addCriterion("R_DT <>", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtGreaterThan(Date value) {
            addCriterion("R_DT >", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtGreaterThanOrEqualTo(Date value) {
            addCriterion("R_DT >=", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtLessThan(Date value) {
            addCriterion("R_DT <", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtLessThanOrEqualTo(Date value) {
            addCriterion("R_DT <=", value, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtIn(List<Date> values) {
            addCriterion("R_DT in", values, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtNotIn(List<Date> values) {
            addCriterion("R_DT not in", values, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtBetween(Date value1, Date value2) {
            addCriterion("R_DT between", value1, value2, "rDt");
            return (Criteria) this;
        }

        public Criteria andRDtNotBetween(Date value1, Date value2) {
            addCriterion("R_DT not between", value1, value2, "rDt");
            return (Criteria) this;
        }

        public Criteria andRIdIsNull() {
            addCriterion("R_ID is null");
            return (Criteria) this;
        }

        public Criteria andRIdIsNotNull() {
            addCriterion("R_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRIdEqualTo(String value) {
            addCriterion("R_ID =", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotEqualTo(String value) {
            addCriterion("R_ID <>", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThan(String value) {
            addCriterion("R_ID >", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdGreaterThanOrEqualTo(String value) {
            addCriterion("R_ID >=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThan(String value) {
            addCriterion("R_ID <", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLessThanOrEqualTo(String value) {
            addCriterion("R_ID <=", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdLike(String value) {
            addCriterion("R_ID like", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotLike(String value) {
            addCriterion("R_ID not like", value, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdIn(List<String> values) {
            addCriterion("R_ID in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotIn(List<String> values) {
            addCriterion("R_ID not in", values, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdBetween(String value1, String value2) {
            addCriterion("R_ID between", value1, value2, "rId");
            return (Criteria) this;
        }

        public Criteria andRIdNotBetween(String value1, String value2) {
            addCriterion("R_ID not between", value1, value2, "rId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table puid_check
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 26 14:39:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table puid_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}