package com.tbe.beans;

import java.util.Date;

public class PUID {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String puid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.ZD_Code
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String zdCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.Machine_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String machineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.O_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Date oDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.Operator_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.Pass_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Date passDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.R_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Date rDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column puid_check.R_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String rId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.ID
     *
     * @return the value of puid_check.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.ID
     *
     * @param id the value for puid_check.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.PUID
     *
     * @return the value of puid_check.PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getPuid() {
        return puid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.PUID
     *
     * @param puid the value for puid_check.PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setPuid(String puid) {
        this.puid = puid == null ? null : puid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.ZD_Code
     *
     * @return the value of puid_check.ZD_Code
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getZdCode() {
        return zdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.ZD_Code
     *
     * @param zdCode the value for puid_check.ZD_Code
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setZdCode(String zdCode) {
        this.zdCode = zdCode == null ? null : zdCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.Machine_ID
     *
     * @return the value of puid_check.Machine_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getMachineId() {
        return machineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.Machine_ID
     *
     * @param machineId the value for puid_check.Machine_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setMachineId(String machineId) {
        this.machineId = machineId == null ? null : machineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.O_DT
     *
     * @return the value of puid_check.O_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Date getoDt() {
        return oDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.O_DT
     *
     * @param oDt the value for puid_check.O_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setoDt(Date oDt) {
        this.oDt = oDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.Operator_ID
     *
     * @return the value of puid_check.Operator_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.Operator_ID
     *
     * @param operatorId the value for puid_check.Operator_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.Pass_DT
     *
     * @return the value of puid_check.Pass_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Date getPassDt() {
        return passDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.Pass_DT
     *
     * @param passDt the value for puid_check.Pass_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setPassDt(Date passDt) {
        this.passDt = passDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.Check_ID
     *
     * @return the value of puid_check.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.Check_ID
     *
     * @param checkId the value for puid_check.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.R_DT
     *
     * @return the value of puid_check.R_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Date getrDt() {
        return rDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.R_DT
     *
     * @param rDt the value for puid_check.R_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setrDt(Date rDt) {
        this.rDt = rDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column puid_check.R_ID
     *
     * @return the value of puid_check.R_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column puid_check.R_ID
     *
     * @param rId the value for puid_check.R_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setrId(String rId) {
        this.rId = rId == null ? null : rId.trim();
    }
}