package com.tbe.beans;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Source_PUID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String sourcePuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Scan_Puid
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String scanPuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Scan_2D
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String scan2d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Machine_Name
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String machineName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Pass_Fail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String passFail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.P_R
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String pR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Check_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Date checkDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Check_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String checkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Unlock_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Date unlockDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Unlock_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String unlockId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.O_Reason
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String oReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.O_Handle
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String oHandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.O_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private String oId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.O_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Date oDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.mail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    private Integer mail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.ID
     *
     * @return the value of records.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.ID
     *
     * @param id the value for records.ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Source_PUID
     *
     * @return the value of records.Source_PUID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getSourcePuid() {
        return sourcePuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Source_PUID
     *
     * @param sourcePuid the value for records.Source_PUID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setSourcePuid(String sourcePuid) {
        this.sourcePuid = sourcePuid == null ? null : sourcePuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Scan_Puid
     *
     * @return the value of records.Scan_Puid
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getScanPuid() {
        return scanPuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Scan_Puid
     *
     * @param scanPuid the value for records.Scan_Puid
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setScanPuid(String scanPuid) {
        this.scanPuid = scanPuid == null ? null : scanPuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Scan_2D
     *
     * @return the value of records.Scan_2D
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getScan2d() {
        return scan2d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Scan_2D
     *
     * @param scan2d the value for records.Scan_2D
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setScan2d(String scan2d) {
        this.scan2d = scan2d == null ? null : scan2d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Machine_Name
     *
     * @return the value of records.Machine_Name
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getMachineName() {
        return machineName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Machine_Name
     *
     * @param machineName the value for records.Machine_Name
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setMachineName(String machineName) {
        this.machineName = machineName == null ? null : machineName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Pass_Fail
     *
     * @return the value of records.Pass_Fail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getPassFail() {
        return passFail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Pass_Fail
     *
     * @param passFail the value for records.Pass_Fail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setPassFail(String passFail) {
        this.passFail = passFail == null ? null : passFail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.P_R
     *
     * @return the value of records.P_R
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getpR() {
        return pR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.P_R
     *
     * @param pR the value for records.P_R
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setpR(String pR) {
        this.pR = pR == null ? null : pR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Check_DT
     *
     * @return the value of records.Check_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Date getCheckDt() {
        return checkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Check_DT
     *
     * @param checkDt the value for records.Check_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setCheckDt(Date checkDt) {
        this.checkDt = checkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Check_ID
     *
     * @return the value of records.Check_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Check_ID
     *
     * @param checkId the value for records.Check_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Unlock_DT
     *
     * @return the value of records.Unlock_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Date getUnlockDt() {
        return unlockDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Unlock_DT
     *
     * @param unlockDt the value for records.Unlock_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setUnlockDt(Date unlockDt) {
        this.unlockDt = unlockDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Unlock_ID
     *
     * @return the value of records.Unlock_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getUnlockId() {
        return unlockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Unlock_ID
     *
     * @param unlockId the value for records.Unlock_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setUnlockId(String unlockId) {
        this.unlockId = unlockId == null ? null : unlockId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.O_Reason
     *
     * @return the value of records.O_Reason
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getoReason() {
        return oReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.O_Reason
     *
     * @param oReason the value for records.O_Reason
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setoReason(String oReason) {
        this.oReason = oReason == null ? null : oReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.O_Handle
     *
     * @return the value of records.O_Handle
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getoHandle() {
        return oHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.O_Handle
     *
     * @param oHandle the value for records.O_Handle
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setoHandle(String oHandle) {
        this.oHandle = oHandle == null ? null : oHandle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.O_ID
     *
     * @return the value of records.O_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.O_ID
     *
     * @param oId the value for records.O_ID
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.O_DT
     *
     * @return the value of records.O_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Date getoDt() {
        return oDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.O_DT
     *
     * @param oDt the value for records.O_DT
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setoDt(Date oDt) {
        this.oDt = oDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.mail
     *
     * @return the value of records.mail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public Integer getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.mail
     *
     * @param mail the value for records.mail
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    public void setMail(Integer mail) {
        this.mail = mail;
    }
}