package com.tbe.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:58 CST 2019
     */
    public RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIsNull() {
            addCriterion("Source_PUID is null");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIsNotNull() {
            addCriterion("Source_PUID is not null");
            return (Criteria) this;
        }

        public Criteria andSourcePuidEqualTo(String value) {
            addCriterion("Source_PUID =", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotEqualTo(String value) {
            addCriterion("Source_PUID <>", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidGreaterThan(String value) {
            addCriterion("Source_PUID >", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidGreaterThanOrEqualTo(String value) {
            addCriterion("Source_PUID >=", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLessThan(String value) {
            addCriterion("Source_PUID <", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLessThanOrEqualTo(String value) {
            addCriterion("Source_PUID <=", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLike(String value) {
            addCriterion("Source_PUID like", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotLike(String value) {
            addCriterion("Source_PUID not like", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIn(List<String> values) {
            addCriterion("Source_PUID in", values, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotIn(List<String> values) {
            addCriterion("Source_PUID not in", values, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidBetween(String value1, String value2) {
            addCriterion("Source_PUID between", value1, value2, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotBetween(String value1, String value2) {
            addCriterion("Source_PUID not between", value1, value2, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidIsNull() {
            addCriterion("Scan_Puid is null");
            return (Criteria) this;
        }

        public Criteria andScanPuidIsNotNull() {
            addCriterion("Scan_Puid is not null");
            return (Criteria) this;
        }

        public Criteria andScanPuidEqualTo(String value) {
            addCriterion("Scan_Puid =", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotEqualTo(String value) {
            addCriterion("Scan_Puid <>", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidGreaterThan(String value) {
            addCriterion("Scan_Puid >", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidGreaterThanOrEqualTo(String value) {
            addCriterion("Scan_Puid >=", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLessThan(String value) {
            addCriterion("Scan_Puid <", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLessThanOrEqualTo(String value) {
            addCriterion("Scan_Puid <=", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLike(String value) {
            addCriterion("Scan_Puid like", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotLike(String value) {
            addCriterion("Scan_Puid not like", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidIn(List<String> values) {
            addCriterion("Scan_Puid in", values, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotIn(List<String> values) {
            addCriterion("Scan_Puid not in", values, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidBetween(String value1, String value2) {
            addCriterion("Scan_Puid between", value1, value2, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotBetween(String value1, String value2) {
            addCriterion("Scan_Puid not between", value1, value2, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScan2dIsNull() {
            addCriterion("Scan_2D is null");
            return (Criteria) this;
        }

        public Criteria andScan2dIsNotNull() {
            addCriterion("Scan_2D is not null");
            return (Criteria) this;
        }

        public Criteria andScan2dEqualTo(String value) {
            addCriterion("Scan_2D =", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotEqualTo(String value) {
            addCriterion("Scan_2D <>", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dGreaterThan(String value) {
            addCriterion("Scan_2D >", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dGreaterThanOrEqualTo(String value) {
            addCriterion("Scan_2D >=", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLessThan(String value) {
            addCriterion("Scan_2D <", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLessThanOrEqualTo(String value) {
            addCriterion("Scan_2D <=", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLike(String value) {
            addCriterion("Scan_2D like", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotLike(String value) {
            addCriterion("Scan_2D not like", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dIn(List<String> values) {
            addCriterion("Scan_2D in", values, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotIn(List<String> values) {
            addCriterion("Scan_2D not in", values, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dBetween(String value1, String value2) {
            addCriterion("Scan_2D between", value1, value2, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotBetween(String value1, String value2) {
            addCriterion("Scan_2D not between", value1, value2, "scan2d");
            return (Criteria) this;
        }

        public Criteria andMachineNameIsNull() {
            addCriterion("Machine_Name is null");
            return (Criteria) this;
        }

        public Criteria andMachineNameIsNotNull() {
            addCriterion("Machine_Name is not null");
            return (Criteria) this;
        }

        public Criteria andMachineNameEqualTo(String value) {
            addCriterion("Machine_Name =", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameNotEqualTo(String value) {
            addCriterion("Machine_Name <>", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameGreaterThan(String value) {
            addCriterion("Machine_Name >", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameGreaterThanOrEqualTo(String value) {
            addCriterion("Machine_Name >=", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameLessThan(String value) {
            addCriterion("Machine_Name <", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameLessThanOrEqualTo(String value) {
            addCriterion("Machine_Name <=", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameLike(String value) {
            addCriterion("Machine_Name like", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameNotLike(String value) {
            addCriterion("Machine_Name not like", value, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameIn(List<String> values) {
            addCriterion("Machine_Name in", values, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameNotIn(List<String> values) {
            addCriterion("Machine_Name not in", values, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameBetween(String value1, String value2) {
            addCriterion("Machine_Name between", value1, value2, "machineName");
            return (Criteria) this;
        }

        public Criteria andMachineNameNotBetween(String value1, String value2) {
            addCriterion("Machine_Name not between", value1, value2, "machineName");
            return (Criteria) this;
        }

        public Criteria andPassFailIsNull() {
            addCriterion("Pass_Fail is null");
            return (Criteria) this;
        }

        public Criteria andPassFailIsNotNull() {
            addCriterion("Pass_Fail is not null");
            return (Criteria) this;
        }

        public Criteria andPassFailEqualTo(String value) {
            addCriterion("Pass_Fail =", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotEqualTo(String value) {
            addCriterion("Pass_Fail <>", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailGreaterThan(String value) {
            addCriterion("Pass_Fail >", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailGreaterThanOrEqualTo(String value) {
            addCriterion("Pass_Fail >=", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLessThan(String value) {
            addCriterion("Pass_Fail <", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLessThanOrEqualTo(String value) {
            addCriterion("Pass_Fail <=", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLike(String value) {
            addCriterion("Pass_Fail like", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotLike(String value) {
            addCriterion("Pass_Fail not like", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailIn(List<String> values) {
            addCriterion("Pass_Fail in", values, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotIn(List<String> values) {
            addCriterion("Pass_Fail not in", values, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailBetween(String value1, String value2) {
            addCriterion("Pass_Fail between", value1, value2, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotBetween(String value1, String value2) {
            addCriterion("Pass_Fail not between", value1, value2, "passFail");
            return (Criteria) this;
        }

        public Criteria andPRIsNull() {
            addCriterion("P_R is null");
            return (Criteria) this;
        }

        public Criteria andPRIsNotNull() {
            addCriterion("P_R is not null");
            return (Criteria) this;
        }

        public Criteria andPREqualTo(String value) {
            addCriterion("P_R =", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRNotEqualTo(String value) {
            addCriterion("P_R <>", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRGreaterThan(String value) {
            addCriterion("P_R >", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRGreaterThanOrEqualTo(String value) {
            addCriterion("P_R >=", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRLessThan(String value) {
            addCriterion("P_R <", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRLessThanOrEqualTo(String value) {
            addCriterion("P_R <=", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRLike(String value) {
            addCriterion("P_R like", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRNotLike(String value) {
            addCriterion("P_R not like", value, "pR");
            return (Criteria) this;
        }

        public Criteria andPRIn(List<String> values) {
            addCriterion("P_R in", values, "pR");
            return (Criteria) this;
        }

        public Criteria andPRNotIn(List<String> values) {
            addCriterion("P_R not in", values, "pR");
            return (Criteria) this;
        }

        public Criteria andPRBetween(String value1, String value2) {
            addCriterion("P_R between", value1, value2, "pR");
            return (Criteria) this;
        }

        public Criteria andPRNotBetween(String value1, String value2) {
            addCriterion("P_R not between", value1, value2, "pR");
            return (Criteria) this;
        }

        public Criteria andCheckDtIsNull() {
            addCriterion("Check_DT is null");
            return (Criteria) this;
        }

        public Criteria andCheckDtIsNotNull() {
            addCriterion("Check_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDtEqualTo(Date value) {
            addCriterion("Check_DT =", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotEqualTo(Date value) {
            addCriterion("Check_DT <>", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtGreaterThan(Date value) {
            addCriterion("Check_DT >", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtGreaterThanOrEqualTo(Date value) {
            addCriterion("Check_DT >=", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtLessThan(Date value) {
            addCriterion("Check_DT <", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtLessThanOrEqualTo(Date value) {
            addCriterion("Check_DT <=", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtIn(List<Date> values) {
            addCriterion("Check_DT in", values, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotIn(List<Date> values) {
            addCriterion("Check_DT not in", values, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtBetween(Date value1, Date value2) {
            addCriterion("Check_DT between", value1, value2, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotBetween(Date value1, Date value2) {
            addCriterion("Check_DT not between", value1, value2, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("Check_ID is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("Check_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("Check_ID =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("Check_ID <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("Check_ID >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("Check_ID >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("Check_ID <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("Check_ID <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("Check_ID like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("Check_ID not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("Check_ID in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("Check_ID not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("Check_ID between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("Check_ID not between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andUnlockDtIsNull() {
            addCriterion("Unlock_DT is null");
            return (Criteria) this;
        }

        public Criteria andUnlockDtIsNotNull() {
            addCriterion("Unlock_DT is not null");
            return (Criteria) this;
        }

        public Criteria andUnlockDtEqualTo(Date value) {
            addCriterion("Unlock_DT =", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtNotEqualTo(Date value) {
            addCriterion("Unlock_DT <>", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtGreaterThan(Date value) {
            addCriterion("Unlock_DT >", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtGreaterThanOrEqualTo(Date value) {
            addCriterion("Unlock_DT >=", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtLessThan(Date value) {
            addCriterion("Unlock_DT <", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtLessThanOrEqualTo(Date value) {
            addCriterion("Unlock_DT <=", value, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtIn(List<Date> values) {
            addCriterion("Unlock_DT in", values, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtNotIn(List<Date> values) {
            addCriterion("Unlock_DT not in", values, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtBetween(Date value1, Date value2) {
            addCriterion("Unlock_DT between", value1, value2, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockDtNotBetween(Date value1, Date value2) {
            addCriterion("Unlock_DT not between", value1, value2, "unlockDt");
            return (Criteria) this;
        }

        public Criteria andUnlockIdIsNull() {
            addCriterion("Unlock_ID is null");
            return (Criteria) this;
        }

        public Criteria andUnlockIdIsNotNull() {
            addCriterion("Unlock_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUnlockIdEqualTo(String value) {
            addCriterion("Unlock_ID =", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdNotEqualTo(String value) {
            addCriterion("Unlock_ID <>", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdGreaterThan(String value) {
            addCriterion("Unlock_ID >", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdGreaterThanOrEqualTo(String value) {
            addCriterion("Unlock_ID >=", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdLessThan(String value) {
            addCriterion("Unlock_ID <", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdLessThanOrEqualTo(String value) {
            addCriterion("Unlock_ID <=", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdLike(String value) {
            addCriterion("Unlock_ID like", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdNotLike(String value) {
            addCriterion("Unlock_ID not like", value, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdIn(List<String> values) {
            addCriterion("Unlock_ID in", values, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdNotIn(List<String> values) {
            addCriterion("Unlock_ID not in", values, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdBetween(String value1, String value2) {
            addCriterion("Unlock_ID between", value1, value2, "unlockId");
            return (Criteria) this;
        }

        public Criteria andUnlockIdNotBetween(String value1, String value2) {
            addCriterion("Unlock_ID not between", value1, value2, "unlockId");
            return (Criteria) this;
        }

        public Criteria andOReasonIsNull() {
            addCriterion("O_Reason is null");
            return (Criteria) this;
        }

        public Criteria andOReasonIsNotNull() {
            addCriterion("O_Reason is not null");
            return (Criteria) this;
        }

        public Criteria andOReasonEqualTo(String value) {
            addCriterion("O_Reason =", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonNotEqualTo(String value) {
            addCriterion("O_Reason <>", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonGreaterThan(String value) {
            addCriterion("O_Reason >", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonGreaterThanOrEqualTo(String value) {
            addCriterion("O_Reason >=", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonLessThan(String value) {
            addCriterion("O_Reason <", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonLessThanOrEqualTo(String value) {
            addCriterion("O_Reason <=", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonLike(String value) {
            addCriterion("O_Reason like", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonNotLike(String value) {
            addCriterion("O_Reason not like", value, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonIn(List<String> values) {
            addCriterion("O_Reason in", values, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonNotIn(List<String> values) {
            addCriterion("O_Reason not in", values, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonBetween(String value1, String value2) {
            addCriterion("O_Reason between", value1, value2, "oReason");
            return (Criteria) this;
        }

        public Criteria andOReasonNotBetween(String value1, String value2) {
            addCriterion("O_Reason not between", value1, value2, "oReason");
            return (Criteria) this;
        }

        public Criteria andOHandleIsNull() {
            addCriterion("O_Handle is null");
            return (Criteria) this;
        }

        public Criteria andOHandleIsNotNull() {
            addCriterion("O_Handle is not null");
            return (Criteria) this;
        }

        public Criteria andOHandleEqualTo(String value) {
            addCriterion("O_Handle =", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleNotEqualTo(String value) {
            addCriterion("O_Handle <>", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleGreaterThan(String value) {
            addCriterion("O_Handle >", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleGreaterThanOrEqualTo(String value) {
            addCriterion("O_Handle >=", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleLessThan(String value) {
            addCriterion("O_Handle <", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleLessThanOrEqualTo(String value) {
            addCriterion("O_Handle <=", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleLike(String value) {
            addCriterion("O_Handle like", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleNotLike(String value) {
            addCriterion("O_Handle not like", value, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleIn(List<String> values) {
            addCriterion("O_Handle in", values, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleNotIn(List<String> values) {
            addCriterion("O_Handle not in", values, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleBetween(String value1, String value2) {
            addCriterion("O_Handle between", value1, value2, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOHandleNotBetween(String value1, String value2) {
            addCriterion("O_Handle not between", value1, value2, "oHandle");
            return (Criteria) this;
        }

        public Criteria andOIdIsNull() {
            addCriterion("O_ID is null");
            return (Criteria) this;
        }

        public Criteria andOIdIsNotNull() {
            addCriterion("O_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOIdEqualTo(String value) {
            addCriterion("O_ID =", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotEqualTo(String value) {
            addCriterion("O_ID <>", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThan(String value) {
            addCriterion("O_ID >", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdGreaterThanOrEqualTo(String value) {
            addCriterion("O_ID >=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThan(String value) {
            addCriterion("O_ID <", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLessThanOrEqualTo(String value) {
            addCriterion("O_ID <=", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdLike(String value) {
            addCriterion("O_ID like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotLike(String value) {
            addCriterion("O_ID not like", value, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdIn(List<String> values) {
            addCriterion("O_ID in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotIn(List<String> values) {
            addCriterion("O_ID not in", values, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdBetween(String value1, String value2) {
            addCriterion("O_ID between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andOIdNotBetween(String value1, String value2) {
            addCriterion("O_ID not between", value1, value2, "oId");
            return (Criteria) this;
        }

        public Criteria andODtIsNull() {
            addCriterion("O_DT is null");
            return (Criteria) this;
        }

        public Criteria andODtIsNotNull() {
            addCriterion("O_DT is not null");
            return (Criteria) this;
        }

        public Criteria andODtEqualTo(Date value) {
            addCriterion("O_DT =", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotEqualTo(Date value) {
            addCriterion("O_DT <>", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtGreaterThan(Date value) {
            addCriterion("O_DT >", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtGreaterThanOrEqualTo(Date value) {
            addCriterion("O_DT >=", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtLessThan(Date value) {
            addCriterion("O_DT <", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtLessThanOrEqualTo(Date value) {
            addCriterion("O_DT <=", value, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtIn(List<Date> values) {
            addCriterion("O_DT in", values, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotIn(List<Date> values) {
            addCriterion("O_DT not in", values, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtBetween(Date value1, Date value2) {
            addCriterion("O_DT between", value1, value2, "oDt");
            return (Criteria) this;
        }

        public Criteria andODtNotBetween(Date value1, Date value2) {
            addCriterion("O_DT not between", value1, value2, "oDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated do_not_delete_during_merge Fri May 10 08:07:59 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated Fri May 10 08:07:59 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}