package com.tbe.beans;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Source_PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String sourcePuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Scan_Puid
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String scanPuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Scan_2D
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String scan2d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Pass_Fail
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String passFail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Reason
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Check_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Date checkDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column records.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String checkId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.ID
     *
     * @return the value of records.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.ID
     *
     * @param id the value for records.ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Source_PUID
     *
     * @return the value of records.Source_PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getSourcePuid() {
        return sourcePuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Source_PUID
     *
     * @param sourcePuid the value for records.Source_PUID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setSourcePuid(String sourcePuid) {
        this.sourcePuid = sourcePuid == null ? null : sourcePuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Scan_Puid
     *
     * @return the value of records.Scan_Puid
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getScanPuid() {
        return scanPuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Scan_Puid
     *
     * @param scanPuid the value for records.Scan_Puid
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setScanPuid(String scanPuid) {
        this.scanPuid = scanPuid == null ? null : scanPuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Scan_2D
     *
     * @return the value of records.Scan_2D
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getScan2d() {
        return scan2d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Scan_2D
     *
     * @param scan2d the value for records.Scan_2D
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setScan2d(String scan2d) {
        this.scan2d = scan2d == null ? null : scan2d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Pass_Fail
     *
     * @return the value of records.Pass_Fail
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getPassFail() {
        return passFail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Pass_Fail
     *
     * @param passFail the value for records.Pass_Fail
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setPassFail(String passFail) {
        this.passFail = passFail == null ? null : passFail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Reason
     *
     * @return the value of records.Reason
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Reason
     *
     * @param reason the value for records.Reason
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Check_DT
     *
     * @return the value of records.Check_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Date getCheckDt() {
        return checkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Check_DT
     *
     * @param checkDt the value for records.Check_DT
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setCheckDt(Date checkDt) {
        this.checkDt = checkDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column records.Check_ID
     *
     * @return the value of records.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getCheckId() {
        return checkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column records.Check_ID
     *
     * @param checkId the value for records.Check_ID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setCheckId(String checkId) {
        this.checkId = checkId == null ? null : checkId.trim();
    }
}