package com.tbe.beans;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public RecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIsNull() {
            addCriterion("Source_PUID is null");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIsNotNull() {
            addCriterion("Source_PUID is not null");
            return (Criteria) this;
        }

        public Criteria andSourcePuidEqualTo(String value) {
            addCriterion("Source_PUID =", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotEqualTo(String value) {
            addCriterion("Source_PUID <>", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidGreaterThan(String value) {
            addCriterion("Source_PUID >", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidGreaterThanOrEqualTo(String value) {
            addCriterion("Source_PUID >=", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLessThan(String value) {
            addCriterion("Source_PUID <", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLessThanOrEqualTo(String value) {
            addCriterion("Source_PUID <=", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidLike(String value) {
            addCriterion("Source_PUID like", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotLike(String value) {
            addCriterion("Source_PUID not like", value, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidIn(List<String> values) {
            addCriterion("Source_PUID in", values, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotIn(List<String> values) {
            addCriterion("Source_PUID not in", values, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidBetween(String value1, String value2) {
            addCriterion("Source_PUID between", value1, value2, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andSourcePuidNotBetween(String value1, String value2) {
            addCriterion("Source_PUID not between", value1, value2, "sourcePuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidIsNull() {
            addCriterion("Scan_Puid is null");
            return (Criteria) this;
        }

        public Criteria andScanPuidIsNotNull() {
            addCriterion("Scan_Puid is not null");
            return (Criteria) this;
        }

        public Criteria andScanPuidEqualTo(String value) {
            addCriterion("Scan_Puid =", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotEqualTo(String value) {
            addCriterion("Scan_Puid <>", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidGreaterThan(String value) {
            addCriterion("Scan_Puid >", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidGreaterThanOrEqualTo(String value) {
            addCriterion("Scan_Puid >=", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLessThan(String value) {
            addCriterion("Scan_Puid <", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLessThanOrEqualTo(String value) {
            addCriterion("Scan_Puid <=", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidLike(String value) {
            addCriterion("Scan_Puid like", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotLike(String value) {
            addCriterion("Scan_Puid not like", value, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidIn(List<String> values) {
            addCriterion("Scan_Puid in", values, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotIn(List<String> values) {
            addCriterion("Scan_Puid not in", values, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidBetween(String value1, String value2) {
            addCriterion("Scan_Puid between", value1, value2, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScanPuidNotBetween(String value1, String value2) {
            addCriterion("Scan_Puid not between", value1, value2, "scanPuid");
            return (Criteria) this;
        }

        public Criteria andScan2dIsNull() {
            addCriterion("Scan_2D is null");
            return (Criteria) this;
        }

        public Criteria andScan2dIsNotNull() {
            addCriterion("Scan_2D is not null");
            return (Criteria) this;
        }

        public Criteria andScan2dEqualTo(String value) {
            addCriterion("Scan_2D =", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotEqualTo(String value) {
            addCriterion("Scan_2D <>", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dGreaterThan(String value) {
            addCriterion("Scan_2D >", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dGreaterThanOrEqualTo(String value) {
            addCriterion("Scan_2D >=", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLessThan(String value) {
            addCriterion("Scan_2D <", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLessThanOrEqualTo(String value) {
            addCriterion("Scan_2D <=", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dLike(String value) {
            addCriterion("Scan_2D like", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotLike(String value) {
            addCriterion("Scan_2D not like", value, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dIn(List<String> values) {
            addCriterion("Scan_2D in", values, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotIn(List<String> values) {
            addCriterion("Scan_2D not in", values, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dBetween(String value1, String value2) {
            addCriterion("Scan_2D between", value1, value2, "scan2d");
            return (Criteria) this;
        }

        public Criteria andScan2dNotBetween(String value1, String value2) {
            addCriterion("Scan_2D not between", value1, value2, "scan2d");
            return (Criteria) this;
        }

        public Criteria andPassFailIsNull() {
            addCriterion("Pass_Fail is null");
            return (Criteria) this;
        }

        public Criteria andPassFailIsNotNull() {
            addCriterion("Pass_Fail is not null");
            return (Criteria) this;
        }

        public Criteria andPassFailEqualTo(String value) {
            addCriterion("Pass_Fail =", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotEqualTo(String value) {
            addCriterion("Pass_Fail <>", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailGreaterThan(String value) {
            addCriterion("Pass_Fail >", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailGreaterThanOrEqualTo(String value) {
            addCriterion("Pass_Fail >=", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLessThan(String value) {
            addCriterion("Pass_Fail <", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLessThanOrEqualTo(String value) {
            addCriterion("Pass_Fail <=", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailLike(String value) {
            addCriterion("Pass_Fail like", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotLike(String value) {
            addCriterion("Pass_Fail not like", value, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailIn(List<String> values) {
            addCriterion("Pass_Fail in", values, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotIn(List<String> values) {
            addCriterion("Pass_Fail not in", values, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailBetween(String value1, String value2) {
            addCriterion("Pass_Fail between", value1, value2, "passFail");
            return (Criteria) this;
        }

        public Criteria andPassFailNotBetween(String value1, String value2) {
            addCriterion("Pass_Fail not between", value1, value2, "passFail");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("Reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("Reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("Reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("Reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("Reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("Reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("Reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("Reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("Reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("Reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("Reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("Reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("Reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("Reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andCheckDtIsNull() {
            addCriterion("Check_DT is null");
            return (Criteria) this;
        }

        public Criteria andCheckDtIsNotNull() {
            addCriterion("Check_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCheckDtEqualTo(Date value) {
            addCriterion("Check_DT =", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotEqualTo(Date value) {
            addCriterion("Check_DT <>", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtGreaterThan(Date value) {
            addCriterion("Check_DT >", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtGreaterThanOrEqualTo(Date value) {
            addCriterion("Check_DT >=", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtLessThan(Date value) {
            addCriterion("Check_DT <", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtLessThanOrEqualTo(Date value) {
            addCriterion("Check_DT <=", value, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtIn(List<Date> values) {
            addCriterion("Check_DT in", values, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotIn(List<Date> values) {
            addCriterion("Check_DT not in", values, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtBetween(Date value1, Date value2) {
            addCriterion("Check_DT between", value1, value2, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckDtNotBetween(Date value1, Date value2) {
            addCriterion("Check_DT not between", value1, value2, "checkDt");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNull() {
            addCriterion("Check_ID is null");
            return (Criteria) this;
        }

        public Criteria andCheckIdIsNotNull() {
            addCriterion("Check_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCheckIdEqualTo(String value) {
            addCriterion("Check_ID =", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotEqualTo(String value) {
            addCriterion("Check_ID <>", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThan(String value) {
            addCriterion("Check_ID >", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdGreaterThanOrEqualTo(String value) {
            addCriterion("Check_ID >=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThan(String value) {
            addCriterion("Check_ID <", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLessThanOrEqualTo(String value) {
            addCriterion("Check_ID <=", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdLike(String value) {
            addCriterion("Check_ID like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotLike(String value) {
            addCriterion("Check_ID not like", value, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdIn(List<String> values) {
            addCriterion("Check_ID in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotIn(List<String> values) {
            addCriterion("Check_ID not in", values, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdBetween(String value1, String value2) {
            addCriterion("Check_ID between", value1, value2, "checkId");
            return (Criteria) this;
        }

        public Criteria andCheckIdNotBetween(String value1, String value2) {
            addCriterion("Check_ID not between", value1, value2, "checkId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated do_not_delete_during_merge Fri Apr 26 14:39:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table records
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}