package com.tbe.beans;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pw_check.CoreID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String coreid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pw_check.UserName
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pw_check.PW
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private String pw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pw_check.LV
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    private Integer lv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pw_check.CoreID
     *
     * @return the value of pw_check.CoreID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getCoreid() {
        return coreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pw_check.CoreID
     *
     * @param coreid the value for pw_check.CoreID
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setCoreid(String coreid) {
        this.coreid = coreid == null ? null : coreid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pw_check.UserName
     *
     * @return the value of pw_check.UserName
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pw_check.UserName
     *
     * @param username the value for pw_check.UserName
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pw_check.PW
     *
     * @return the value of pw_check.PW
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public String getPw() {
        return pw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pw_check.PW
     *
     * @param pw the value for pw_check.PW
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setPw(String pw) {
        this.pw = pw == null ? null : pw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pw_check.LV
     *
     * @return the value of pw_check.LV
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public Integer getLv() {
        return lv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pw_check.LV
     *
     * @param lv the value for pw_check.LV
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    public void setLv(Integer lv) {
        this.lv = lv;
    }
}