package com.tbe.dao;

import com.tbe.beans.Local;
import com.tbe.beans.LocalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    long countByExample(LocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int deleteByExample(LocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int insert(Local record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int insertSelective(Local record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    List<Local> selectByExample(LocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    Local selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") Local record, @Param("example") LocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int updateByExample(@Param("record") Local record, @Param("example") LocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int updateByPrimaryKeySelective(Local record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table local
     *
     * @mbg.generated Tue May 14 11:30:42 CST 2019
     */
    int updateByPrimaryKey(Local record);
}