package com.tbe.dao;

import com.tbe.beans.Machine;
import com.tbe.beans.MachineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MachineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    long countByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int deleteByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int insert(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int insertSelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    List<Machine> selectByExample(MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    Machine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByExample(@Param("record") Machine record, @Param("example") MachineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByPrimaryKeySelective(Machine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table machine_tb
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByPrimaryKey(Machine record);
}