package com.tbe.dao;

import com.tbe.beans.User;
import com.tbe.beans.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pw_check
     *
     * @mbg.generated Fri Apr 26 14:39:19 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}